### ISSUE TITLE
Cannot read property 'then' of undefined on 3.0.0-beta.17

### ISSUE THREAD

**Issue by crowmw** [maxmantz/redux-oidc#100] opened 2018-04-17 13:55 UTC
version: 3.0.0-beta.17

On main index.js in `componentWillMount` i want to fetch data. Dispatching actionCreator that returns Promise. Using `then` to do othe stuff after that.

In callback.js (CallbackComponent) i doing successCallback redirect to index.js using `this.context.router.push`

on version 2.2.0, everything works fine, but after update i getting an error:

```console
Uncaught TypeError: Cannot read property 'then' of undefined
    at agentPanel.componentDidMount (index.js:38)
    at ReactCompositeComponent.js:265
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponent.js:264
    at CallbackQueue.notifyAll (CallbackQueue.js:76)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:80)
    at ReactReconcileTransaction.closeAll (Transaction.js:206)
    at ReactReconcileTransaction.perform (Transaction.js:153)
    at batchedMountComponentIntoNode (ReactMount.js:126)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:140)
```

CallbackComponent have userManager in props. Any ideas?

**Comment by maxmantz** [comment] 2018-04-26 08:40
No. From the error message I cannot defer what the cause may be. You'll have to provide additional information.

**Comment by maxmantz** [comment] 2018-05-07 13:58
I'll close this for now. Feel free to comment if you have more info to share.

**Closed by maxmantz** 2018-05-07 13:58 UTC
Labels: question
