### ISSUE TITLE
LoadUser return null after login

### ISSUE THREAD

**Issue by bohdanbirdie** [maxmantz/redux-oidc#96] opened 2018-03-13 15:18 UTC
`user` is `null` when loading for the first time after login redirect
```JSON
"redux-oidc": "^3.0.0-beta.16",
"oidc-client": "^1.4.1"
```

```JavaScript
loadUser(store, userManager)
  .then((user) => {
    console.log('USER_FOUND', user);
    if (user) {
      store.dispatch({
        type: 'redux-oidc/USER_FOUND',
        payload: user,
      });
    }
  }).catch((err) => {
    console.log(err);
  });
```

___
Or maybe someone can suggest a better way to call actions right after `redux-oidc/USER_FOUND`?

**Comment by maxmantz** [comment] 2018-03-14 13:13
This should not happen. Can you reproduce this error in a PR of the example app?

**Comment by bohdanbirdie** [comment] 2018-03-14 13:17
@maxmantz I can provide more details, but not sure that will be able to reproduce it with an external app.

**Comment by maxmantz** [comment] 2018-03-14 13:50
Sorry for the confusion. No need for a PR - I think I understand what the problem is.. `loadUser` checks sessionStorage or localStorage for existing user data. If no user is present, then `null` is returned. So it is possible, that `loadUser` returns null after a login redirect, because it is most likely running prior to the `<CallbackComponent />` doing its job.

I still don't understand your second question though...

**Comment by bohdanbirdie** [comment] 2018-03-14 13:56
@maxmantz well, I was looking for better way to fire some of my actions after `redux-oidc/USER_FOUND` was dispatched
Let's say that I need to init some fetching from the server once user logged in, and I want to do it from redux(and don't want to do it from the component like with `componentWillMount` and etc)
So what is the best way to fire some action after `redux-oidc/USER_FOUND` dispatched?

**Comment by maxmantz** [comment] 2018-03-14 14:23
`loadUser` dispatches the found user with the `redux-oidc/USER_FOUND` action by itself (the payload should never be null, though!). So you don't need to use the promise callback from `loadUser` directly. You can listen to that action type from where ever you like and do other stuff there.

**Comment by reggieboyYEAH** [comment] 2018-03-21 08:55
Hello @maxmantz 

I'm also encountering the same problem. The user is `null` even when is values in LocalStorage

The user managed to login and then after the callback

The url
![image](https://user-images.githubusercontent.com/7448059/37700759-aac2c8ea-2d27-11e8-81d2-38b0f4ca1f2f.png)

The LocalStorage
![image](https://user-images.githubusercontent.com/7448059/37700783-c4363154-2d27-11e8-9fb0-564bdaca627b.png)

The Redux Store
![image](https://user-images.githubusercontent.com/7448059/37700887-10bfe52e-2d28-11e8-855f-61fe5ef91d06.png)


Here is my configuration in the Client

```
const configureOidc = {
    client_id: 'futurestack.web',
    redirect_uri: `${window.location.protocol}//${window.location.hostname}:${window.location.port}/callback`,
    response_type: 'id_token token',
    scope: 'openid profile api1',
    authority: 'http://localhost:5000',
    //post_logout_redirect_uri: `${window.location.protocol}//${window.location.hostname}:${window.location.port}/login`,
    silent_redirect_uri: `${window.location.protocol}//${window.location.hostname}:${window.location.port}/silent_renew.html`,
    automaticSilentRenew: true,
    filterProtocolClaims: true,
    loadUserInfo: true
}


```


Here is my Client Configuration in the Server
I am using ASP.NET Core 2 + Identity Server 4

        ```
                        // JavaScript Client
                new Client
                {
                    ClientId = "futurestack.web",
                    ClientName = "JavaScript Client",
                    AllowedGrantTypes = GrantTypes.Implicit,
                    AllowAccessTokensViaBrowser = true,

                    RedirectUris = {
                        "http://localhost:5050/callback",
                        "http://localhost:5050/silent-renew.html"
                    },
                    PostLogoutRedirectUris = { "http://localhost:5050" },
                    AllowedCorsOrigins = { "http://localhost:5050" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "api1"
                    },

                    AccessTokenLifetime = 300
                }
```

**Comment by reggieboyYEAH** [comment] 2018-03-21 09:38
Btw I observed that my callback component is not being called

**Comment by maxmantz** [comment] 2018-03-21 11:22
@reggieboyYEAH The data in `localStorage` is used by the userManager during auhtentication, user data will be stored in `sessionStorage` by default. I can see that your silent renew urls differ ("silent_renew.html" vs "silent-renew.html". But that is not the issue.

The inspector log shows that the `USER_EXPIRED` event was fired. Since the `<CallbackComponent />` wasn't hit, maybe you have a routing problem? Do you render the routes when no user is present?

**Comment by maxmantz** [comment] 2018-03-27 14:06
I'll close this for now. Feel free to comment should the issue persist.

**Closed by maxmantz** 2018-03-27 14:06 UTC
Labels: question

**Comment by ifeanyilawrence** [comment] 2018-12-20 10:51
@reggieboyYEAH I experience the same issue but resolved it by fixing my route. The callback route was wrong in my case. It is just a routing issue as @maxmantz  pointed out.
