### ISSUE TITLE
processSilentRenew() not executed on token expire

### ISSUE THREAD

**Issue by thidasapankaja** [maxmantz/redux-oidc#158] opened 2019-08-01 07:28 UTC
I've configured redux-oidc with [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) project. I've set _automaticSilentRenew_ true. And I have a folder named silent and there's index.js with

```
import { processSilentRenew } from 'redux-oidc';

processSilentRenew();
```
 and silent.html with
```
<!DOCTYPE html>
<html lang="en">
<body>

</body>
</html>
``` 
in it. I configured the the js file and index file in webpack as well. When I first start the project 
**processSilentRenew();** executes and project loads. But after the timeout, _processSilentRenew();_ is not executing. What maybe the reason ? How can I catch an error or something and figure out the reason ?

Any help would be appreciated.

Thanks

**Comment by maxmantz** [comment] 2019-08-01 16:23
Hi. From the info you've provided it is diffucult to say what the issue is. In addition to the steps you've provided you have to make sure that you set the config value `silent_redirect_uri` to the path where your `silent.html` is located. Also make sure that webpack bundles `silent.html` correctly, since this can be quite tricky.

Other than that I cannot say why this isn't working. You could enable logging for the `userManager` by running this:

```
import { Log } from "oidc-client";
Log.logger = console;
```

Maybe this will give you additional pointers on where to look for troubleshooting.

**Comment by thidasapankaja** [comment] 2019-08-02 06:24
@maxmantz ,

Thank you. 
I configured the log and I'm getting these errors on the log after USER_EXPIRING action is dispatched.

```
Frame window timed out
SilentRenewService._tokenExpiring: Error from signinSilent: Frame window timed out
```

What I'm seeing is my app is not dispatching `redux-oidc/LOADING_USER` action. Should I dispatch it manually ? I've configured the reducer.

**Comment by maxmantz** [comment] 2019-08-02 10:12
This usually hints at something wrong with the bundling of `silent.html`. There are two ways to verify this. In Chrome's devtools when you instpect the HTML, can you see an `<iframe />` in the markup? This is where `silent.html` gets loaded into. When there is an error there, this is why the log message appears. In addition, please check your production build and the files generated by webpack. Is there a `silent.html` in the same folder as the `index.html`?

**Comment by maxmantz** [comment] 2019-08-05 13:48
Closing this for now. If you have further questions, feel free to comment.

**Closed by maxmantz** 2019-08-05 13:48 UTC
Labels: question

**Comment by mukesh210** [comment] 2019-10-18 10:15
@thidasapankaja I am beginner in Javascript. Even though i read Webpack documentation, it is not clear. Can you please help me on how to configure silent_renew html and js file in webpack.
