### ISSUE TITLE
Repeated all the time

### ISSUE THREAD

**Issue by dmpx** [maxmantz/redux-oidc#127] opened 2018-10-11 10:47 UTC
**store.js**

export default function configureStore(history, userManager, initialState) {
  const logger = createLogger()
  const router = routerMiddleware(history)

  const createStoreWithMiddleware = applyMiddleware(
    router,
    thunk,
    logger
  )(createStore)

  const store = createStoreWithMiddleware(
    rootReducer,
    initialState
  )

  loadUser(store, userManager)

  return store
}

**callback.js**

class Callback extends React.Component {
  static propTypes = {
    dispatch: PropTypes.func
  }

  render() {
    // just redirect to '/' in both cases
    return (
      <CallbackComponent
        userManager={userManager}
        successCallback={(user) => this.props.dispatch(push('/'))}
        errorCallback={error => {
          this.props.dispatch(push('/'))
          console.error(error)
        }}
      >
        <div>Redirecting...</div>
      </CallbackComponent>
    )
  }
}

function mapDispatchToProps(dispatch) {
  return {
    dispatch
  }
}

export default connect(null, mapDispatchToProps)(Callback)

**reducer.js**

import { combineReducers } from 'redux'
import { routerReducer as routing } from 'react-router-redux'
import { reducer as oidc } from 'redux-oidc'

const rootReducer = combineReducers({
  routing,
  oidc
})

export default rootReducer

**root.js**

const Root = ({ store, userManager }) =>
  <Provider store={store}>
    <OidcProvider store={store} userManager={userManager}>
        <App />
    </OidcProvider>
  </Provider >

Root.propTypes = {
  userManager: PropTypes.object.isRequired,
  store: PropTypes.object.isRequired
}

export default Root

**app.js**

@connect(
  state => state,
  dispatch => bindActionCreators(globalActions, dispatch)
)
export default class App extends Component {
  static propTypes = {
    oidc: PropTypes.object,
    global: PropTypes.object,
    children: PropTypes.any
  }

  render() {
    const { children, animateCls } = this.props.global
    const { user } = this.props.oidc
    const routes = (
      <Router history={history}>
        <Route render={() => {
          return (          
              <Switch>
                {children}
                <Route path='/callback' component={Callback} />
                <Layout exact path='/' component={Home} />                
              </Switch>
          )
        }} />
      </Router>
    )

    const isValidUserPresent = user && !user.expired
    const isCallbackRouteRequested = location.pathname === '/callback'
    const shouldRenderRoutes = isValidUserPresent || isCallbackRouteRequested
    return shouldRenderRoutes ? routes : userManager.signinRedirect()
  }
}

[https://www.redbon.cn/uploads/redux-oidc.gif](url)

**Comment by maxmantz** [comment] 2018-10-13 11:43
Sorry, but the link to the gif is not working, neither can I see or tell from your code what is repeating all the time nor why it repeats. Please add more info.

**Comment by dmpx** [comment] 2018-10-13 13:02
[https://www.redbon.cn/uploads/redux-oidc.gif](https://www.redbon.cn/uploads/redux-oidc.gif)

OidcProvider Component

componentWillMount() {
    // register the event callbacks
    this.userManager.events.addUserSignedOut(this.onUserSignedOut);
  }

The component will always execute this sentence

reducer

 case USER_SIGNED_OUT:
      return Object.assign({}, { ...state }, { user: null, isLoadingUser: false });

CallbackComponent received User empty

const Root = ({ store }) =>
  <Provider store={store}>    
   <OidcProvider store={store} userManager={userManager}>
      <App />
   <OidcProvider />
  </Provider>

has a problem, Repeat the CallbackComponent 

const Root = ({ store }) =>
  <Provider store={store}>       
      <App />
  </Provider>

Return to normal

**Comment by maxmantz** [comment] 2018-10-15 17:49
Sorry but I do not understand what the issue is and from your description I cannot find that out. I'll close this for now. If you have any information which can help me to solve your issue, feel free to share it here.

**Closed by maxmantz** 2018-10-15 17:49 UTC
