### ISSUE TITLE
Use redux-oidc with SSR

### ISSUE THREAD

**Issue by pellea** [maxmantz/redux-oidc#21] opened 2017-01-12 11:03 UTC
Hello,

I have a react application with Server Side Rendering.
I used the custom InMemoryWebStorage mentionned in a earlier closed GitHub Issues.

```
import { createUserManager } from 'redux-oidc';
import InMemoryStorageStore, { UserManager, WebStorageStateStore } from 'oidc-client';

// create a user manager instance
const config = {
  ...
  userStore: new WebStorageStateStore({ store: InMemoryStorageStore })
}

const userManager : UserManager = createUserManager(config);

export default userManager;
```

But I have this following exception:

```
Call to Node module failed with error: Prerendering failed because of error: ReferenceError: localStorage is not defined
at Function.get (D:\Dev\iNUI\Store\airxtouch\node_modules\oidc-client\lib\oidc-client.min.js:1:12917)
```

What do I missed? How can I solve this?

Thanks.

**Comment by maxmantz** [comment] 2017-01-12 13:31
This is an issue I've been meaning to tackle, I just didn't have the time or someone using SSR to help me with it. But here you are :)

The issue is that this package relies on localStorage to set a key for checking whether or not a token callback has occurred. It is used in [the middlware9(https://github.com/maxmantz/redux-oidc/blob/master/src/oidcMiddleware.js#L34) and the [callback component](https://github.com/maxmantz/redux-oidc/blob/master/src/CallbackComponent.js). We would have to remove this reliance and work with something else.

This "something else" shouldideally be a storage mechanism like the `InMemoryStorageStore` used by oidc-client so you can use one store for both. The problem here is that these stores use promises, so the code would have to be refactored in such a way as to make promises work.

I will look into this as soon as I find the time. Since you would be using it, I'd be grateful for feedback regarding my implementation. Feel free to submit a PR if you feel like you want to contribute. Looking forward to it!

**Comment by pellea** [comment] 2017-01-12 14:33
I tried not to add the OIDC middleware on the server side (only in the configureStore on the client side). It seems to work properly. But the problem occurs with the `userManager.signinRedirect()` in my Login component/page. As soon as I uncomment this line, it crashes.

In my understanding, the problem seems coming from the oidc-client library. Even while specifying the other store "in memory" it doesn't work.

**Comment by pellea** [comment] 2017-01-12 15:21
I tried it here : https://github.com/IdentityModel/oidc-client-js/issues/243

**Comment by maxmantz** [comment] 2017-01-13 17:34
I have published v3.0.0-beta.1 to npm. It is now completely independent from `window`. The API has changed a little which is why I had to bump the version to 3. 

The main changes for your app are that the middleware creator now only needs the userManager as an argument and secondly the `CallbackComponent` needs the userManager as a prop.

I'd be happy for any feedback!

**Comment by pellea** [comment] 2017-01-13 20:12
Thanks for the update! I have this exception with the new v3.0.0-beta.1:

```
Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: regeneratorRuntime is not defined
at Object.defineProperty.value (...\node_modules\redux-oidc\dist\redux-oidc.js:1:9422)
```

**Comment by maxmantz** [comment] 2017-01-13 21:17
You will need the [babel polyfill](https://babeljs.io/docs/usage/polyfill/) for this to work. I'll add it as a peer dependency in the next update.

**Comment by pellea** [comment] 2017-01-13 22:29
I was missing the import on the server side...

I had the other exception with the sessionStorage not defined.
I configure a custom userStore/stateStore for the UserManager (like the other linked GitHub Issue).
```
Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: sessionStorage is not defined
at Function.get (...\node_modules\oidc-client\lib\oidc-client.min.js:1:12982)
```

And then I have this error :
```
Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: XMLHttpRequest is not defined
at Function.get (...\node_modules\oidc-client\lib\oidc-client.min.js:1:13049)
at new t (...\node_modules\oidc-client\lib\oidc-client.min.js:1:24706)
```
But it's not directly related to the redux-oidc library. Did you have this last error? If so, how did you solve it?

Thanks.

**Comment by maxmantz** [comment] 2017-01-13 22:36
Haven't tried SSR myself yet. Maybe this can help? https://www.npmjs.com/package/w3c-xmlhttprequest

**Comment by pellea** [comment] 2017-01-13 22:55
I think at that point the only way to solved this is to replace all the xmlhttprequest inside the oidc-client-js by something else.

If you want to test quickly the SSR without a lot of work you can use the aspnet core generator here : https://www.npmjs.com/package/generator-aspnetcore-spa.

**Comment by pellea** [comment] 2017-01-16 10:40
I modified the source code of oidc-client-js (I replaced the XMLHttpRequest by fecth).

Now I have an other error in this library probably linked to the custom store I used.

```
Uncaught (in promise) Error: Error handling redirect callback: No matching state found in storage
    at r.n.onRedirectError (redux-oidc.js:formatted:1)
    at redux-oidc.js:formatted:1
```

Have you tried this library with a custom store for user/state?

**Comment by maxmantz** [comment] 2017-01-16 15:32
Sorry, can't help you there.

**Comment by pellea** [comment] 2017-01-19 09:41
I have now a working solution (using a modified https://github.com/pellea/oidc-client-js/commit/0c35d47585c1d4ee947cd0d33304a9eb3c1181c2 and using the custom 3.0.0-beta.1 build).

What you have modified in this 3.0.0-beta.1 build seems to be enough in order to use Server Side Rendering.

**Comment by maxmantz** [comment] 2017-01-19 13:09
Good to hear. I'll close this for now.

**Closed by maxmantz** 2017-01-19 13:09 UTC
Labels: enhancement

**Comment by emragins** [comment] 2017-05-16 05:06
@pellea Would you consider a pull request of your changes to IdentityModel/oidc-client-js?  I'm running into the same problems you had.

**Comment by pellea** [comment] 2017-05-16 07:34
I don't think it would be possible. I removed the IoC capabilities of the library (that the original author intended to have). I also renamed the npm package and published it on npm. I don't think that I could make a pull request as-is.

What do you think @brockallen ?

**Comment by Shadowman4205** [comment] 2017-06-13 08:32
@pellea i tried ur way from [here](https://github.com/IdentityModel/oidc-client-js/issues/243). But i get error again 
>ReferenceError: localStorage is not defined

```
import { InMemoryWebStorage } from 'oidc-client';
import MemoryStorage from 'memorystorage'

export default class CustomWebStorageStore extends InMemoryWebStorage
{
    _storage = new MemoryStorage;
    constructor(){
        super()
        this._storage = new MemoryStorage('my-app');
    }
    
    getItem(key) {
        return this._storage.getItem(key);
    }
    
    setItem(key, value){
        this._storage.setItem(key, value);
    }   
    
    removeItem(key){
        this._storage.removeItem(key);
    }
    
    get length() {
        return this._storage.length();
    }
    
    key(index) {
        return this._storage.key(index);
    }
}
```

```
import { createUserManager } from 'redux-oidc';
import { UserManager, WebStorageStateStore, WebStorageStateStoreSettings } from 'oidc-client';
import CustomWebStorageStore  from './CustomWebStorageStore';

const myStore = new customStore();

const settings = 
{
  prefix: "oidc.", 
  store: myStore
};

const userManagerConfig = {
  client_id: 'mvc',
  redirect_uri: `localhost:3001/callback`,
  response_type: 'id_token token',
  scope: 'oopenid profile email api1 api2.read_only',
  authority: 'http://localhost:60388/',
  popup_redirect_uri:"localhost:3001/popup",
  silent_redirect_uri: "localhost:3001/silent",
  automaticSilentRenew: true,
  filterProtocolClaims: true,
  loadUserInfo: true,
  userStore: new WebStorageStateStore(settings)
};

const userManager = createUserManager(userManagerConfig);

export default userManager;
```
What am i missing?

**Comment by Tonvengo** [comment] 2017-07-31 21:39
So what is the best solution right now? 
I am getting `Prerendering failed because of error: ReferenceError: sessionStorage is not defined` error.
I am using this starter template https://github.com/aspnet/JavaScriptServices (react-redux) and trying to setup redux-oidc there.
Thank you in advance.

**Comment by maxmantz** [comment] 2017-08-01 07:09
It appears that your `userManager` still uses the default token storage mechanism, which is `sessionStorage`. Please refer to the [oidc-client](https://github.com/IdentityModel/oidc-client-js) library on how to set up a custom storage mechanism.

**Comment by Tonvengo** [comment] 2017-08-01 18:45
@Shadowman4205 did you manage to create working solution?
When I try to use WebStorageStateStore, WebStorageStateStoreSettings I am getting compile error that redux-oidc has not imported these memebers.

**Comment by Shadowman4205** [comment] 2017-08-02 11:32
No i did not, i started using this [oidc-client-node](https://github.com/edwinf/oidc-client-node)
