### ISSUE TITLE
"LOADING_USER" event fired for every input field in form

### ISSUE THREAD

**Issue by ianbrode** [maxmantz/redux-oidc#38] opened 2017-05-03 13:24 UTC
Good day,

I'm encountered strange behaviour of OIDC middleware. I have a form (made with redux-form) which can be accessed only when user is authorised. By default I check user credentials and if there are none - I kick him to auth.server. So after getting back from callback route, my user sees his form. Everything is fine, but for some reason I get 7 "redux-oidc/LOADING_USER" events. This events are connected with my <Field> components from redux-form (also 7 of them). It doesn't break my workflow, but feels very wrong. Do you have any idea what may be wrong with it?

**Comment by maxmantz** [comment] 2017-05-03 14:01
Hi there!

It does indeed look kind of awkward I agree. The reason for this is probably [this](https://github.com/maxmantz/redux-oidc/blob/master/src/oidcMiddleware.js#L26) line in the middleware. The middleware checks the user each time until a valid user object has been found. It is not a bug per sé, but I agree that this behavior can be improved. I will look into possible solutions for this - maybe setting a flag for disabling future checks.

**Comment by maxmantz** [comment] 2017-05-08 19:01
I've published v3.0.0-beta.7 to npm. It contains a new helper function called `loadUser` which loads the user into the store when present. If you are using silent renew, I recommend using this function as a replacement of the middleware. This will also alleviate the problems you've described.

**Comment by maxmantz** [comment] 2017-05-09 16:58
I'll close this for now. Feel free to contact me again if you have questions about implementing these changes.

**Closed by maxmantz** 2017-05-09 16:58 UTC
Labels: enhancement
